In [1]:
import numpy as np
import pandas as pd
import nltk 

from datetime import datetime

In [2]:
data1 = pd.read_csv('Dataset/Pra-Lebaran/Label Ulang/New/All_Label.csv', sep=";")

In [3]:
def load_data():
    data = pd.concat([data1])
    return data

In [4]:
tweet_df = load_data()

In [5]:
tweet_df.head()

,Tanggal,Tweets,Sentiment,ID,Screen Name,Banyak Retweet,Source,Retweet Status,Hashtags
0,06/05/2021 07:45,"b""@adeweee_ Bansos ga berlaku buat orang yang ...",0.0,"1,39E+18",adekiil,0.0,Twitter for Android,0.0,[]
1,06/05/2021 14:25,"b""@Bams44421380 @aik_arif Tp hubungan antara a...",0.0,"1,39E+18",ngimpikau,0.0,Twitter for Android,0.0,[]
2,07/05/2021 03:47,"b""@bangZhack86 Ada ini, da.\nSurat terbuka kep...",0.0,"1,39E+18",ayah_neisha,0.0,Twitter for Android,0.0,[]
3,06/05/2021 06:47,"b""@geloraco Ada kata cebong si anak madam bans...",0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,09/05/2021 13:53,"b""@henrysubiakto O gitu pak ?! Jd yg \n- tdk k...",0.0,"1,39E+18",fa_fenani,0.0,Twitter for Android,0.0,[]

In [6]:
df  = pd.DataFrame(tweet_df[['Tanggal','Tweets', 'Sentiment','ID', 'Screen Name', 'Banyak Retweet', 'Source', 'Retweet Status', 'Hashtags']])

In [7]:
df

,Tanggal,Tweets,Sentiment,ID,Screen Name,Banyak Retweet,Source,Retweet Status,Hashtags
0,06/05/2021 07:45,"b""@adeweee_ Bansos ga berlaku buat orang yang ...",0.0,"1,39E+18",adekiil,0.0,Twitter for Android,0.0,[]
1,06/05/2021 14:25,"b""@Bams44421380 @aik_arif Tp hubungan antara a...",0.0,"1,39E+18",ngimpikau,0.0,Twitter for Android,0.0,[]
2,07/05/2021 03:47,"b""@bangZhack86 Ada ini, da.\nSurat terbuka kep...",0.0,"1,39E+18",ayah_neisha,0.0,Twitter for Android,0.0,[]
3,06/05/2021 06:47,"b""@geloraco Ada kata cebong si anak madam bans...",0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,09/05/2021 13:53,"b""@henrysubiakto O gitu pak ?! Jd yg \n- tdk k...",0.0,"1,39E+18",fa_fenani,0.0,Twitter for Android,0.0,[]
...,...,...,...,...,...,...,...,...,...
18374,12/05/2021 03:19,b'Selama Ramadhan pemerontah udah menyalurkan ...,1.0,"1,39E+18",Berita_Sumatera,2.0,Twitter for Android,0.0,[]
18375,06/05/2021 05:28,"b'Seperti diketahui, Kemensos saat ini terus m...",1.0,"1,39E+18",kompascom,1.0,dlvr.it,0.0,[]
18376,10/05/2021 12:52,"b'SERMA SUTARYONO,BABINSA KORAMIL 02 BAYAN MEM...",1.0,"1,39E+18",Koramilbayan1,0.0,Twitter for Android,0.0,[]
18377,07/05/2021 04:09,b'Sertu Warsono babinsa Sribit melaksanakan ba...,1.0,"1,39E+18",Kodim_Sragen,0.0,Twitter for Android,0.0,[]
18378,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df.to_csv('Dataset/Pra-Lebaran/Label Ulang/New/All_Label.csv',encoding='utf8', index=False)
df

,Tanggal,Tweets,ID,Screen Name,Banyak Retweet,Source,Retweet Status,Hashtags
0,2021-05-05 23:59:57,b'RT @PutraWadapi: Risma ungkap Data Ganda Pen...,1390093944155828224,hendri_hero,996,Twitter for Android,1,[]
1,2021-05-05 23:59:37,b'RT @RicKY_KCh: uang bansos rakyat miskin dip...,1390093858613075968,SARJANAPUTRA12,34,Twitter for Android,1,[]
2,2021-05-05 23:57:25,"b'RT @RamliRizal: Menurut Mbak Risma ke KPK, d...",1390093305233297410,RamdhaniBrutus,489,Twitter for Android,1,[]
3,2021-05-05 23:56:28,b'RT @BudiSetyarso: Para penyidik yg membongka...,1390093067097493504,rangginaaang,3332,Twitter for Android,1,[]
4,2021-05-05 23:55:57,b'RT @panca66: Perusahaan penyedia paket banso...,1390092937736953860,hdriannur,1730,Twitter for Android,1,[]
...,...,...,...,...,...,...,...,...
855,2021-05-12 00:17:14,"b'RT @twitpos: Madam Bansos kemana rimbanya, a...",1392272621983584257,suka_tx,6,Twitter for Android,1,[]
856,2021-05-12 00:14:57,"b'Kate\xc2\xb2nye sih benar, harus sama\xc2\xb...",1392272044872519681,ali_rasid,0,Twitter for Android,0,[]
857,2021-05-12 00:14:35,b'RT @PutraWadapi: Jokowi Disebut-sebut di Sid...,1392271951616380929,Seftian1892,338,Twitter for Android,1,[]
858,2021-05-12 00:11:19,"b'kecewa banget sama pemerenta, sekaligus sedi...",1392271131999039488,ekarutami,0,Twitter for Android,0,[]
859,2021-05-12 00:02:17,b'RT @PutraWadapi: Jokowi Disebut-sebut di Sid...,1392268858422005766,KavindraOemar,338,Twitter for Android,1,[]